### ISSUE TITLE
Fontify "natively" without mmm-mode

### ISSUE THREAD

**Issue by blaenk** [AdamNiederer/vue-mode#49]
Org mode and markdown-mode both have the ability to fontify a region of their buffer using a specified major mode. For example, in markdown-mode there are codeblocks which can be given a language attribute. markdown-mode is able to map this to a major mode (like this package seems to do as well) and then fontify the region within that codeblock using that mode. I'm not very familiar with mmm-mode, but this might be a simpler, perhaps more efficient way of doing the same thing while shedding the mmm-mode dependency and its associated quirks.

Perhaps both methods are essentially doing it the same way, but it seems like markdown-mode's (adapted from org-mode)'s implementation ([see here](https://github.com/jrblevin/markdown-mode/blob/7050c4d6f160694570c2d1868ddad9a67bb97dd6/markdown-mode.el#L8743)) might be simpler. It might be worth looking into. mmm-mode is huge by comparison, perhaps that's for good reason, which is why it may be worth looking into.

**Comment by AdamNiederer** [comment]
I'm not sure whether this would be an appropriate change for vue-mode. The main problems with mmm-mode arise from trying to use minor modes such as flycheck, company, etc on a single submode, which wouldn't work at all with a native fontification solution. It would also mean I'd have to figure out a way to do indentation, mode functions, etc. without opening an indirect buffer (markdown-mode can do none of that from what I can tell).

mmm-mode also removes a good amount of parsing code which I'd otherwise have to write; I use its overlays and hooked variables for the new indirect editing feature, for example. That's also before we talk about the opportunity cost of adding such a large amount of code to the project to achieve feature parity after removing mmm-mode.

I agree the mmm-mode is large and isn't perfect at virtualizing its submodes, but I think it's an order of magnitude better than anything I could come up with for vue. mmm-mode is also reasonably well-written for a project of its size, and I can continue to improve it if I run into things which would be useful in vue-mode (like [this](https://github.com/purcell/mmm-mode/pull/73))

**Comment by blaenk** [comment]
Fair enough, that sounds reasonable to me 👍
